baseURL = "https://aka-bingo.github.io"
languageCode = "en-us"
title = "BinGo's Blog"
theme = "LeaveIt"

paginate = 12
enableEmoji = true
enableRobotsTXT = true
googleAnalytics = "UA-147430773-2"
disqusShortname = "bingo-1994"

preserveTaxonomyNames = false

RSSLink = "index"

[blackfriday]
  hrefTargetBlank = true
  nofollowLinks = true
  noreferrerLinks = true

[Permalinks]
 posts = "/:year/:month/:filename/"

[menu]
  [[menu.main]]
    name = "Blog"
    url = "/posts/"
    weight = 1

  [[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = 2

  [[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 3

  [[menu.main]]
    name = "RSS"
    url = "/index.xml"
    weight = 4

  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 5

[params]
    since = 2018
    author = "BinGo"                           # Author's name
    avatar = "/images/avatar.png"           # Author's avatar
    subtitle = "Hello & Welcome"         # Subtitle
    cdn_url = ""           # Base CDN URL
    home_mode = "" # post or other

    google_verification = ""
   
    description = "" # site description
    keywords = "" # site keywords

    beian = ""
    baiduAnalytics = "cdf5707c56cd938808f48799af9bc6ff"

    license= '本文采用<a rel="license" href="http://creativecommons.org/licenses/by-nc/4.0/" target="_blank">知识共享署名-非商业性使用 4.0 国际许可协议</a>进行许可'

[params.social]
    GitHub = "AKA-bingo"
    #Twitter = "Bin_G0"
    LinkedIn = ""
    Email   = "icebin000@gmail.com"
    Weibo = "heyimbingo"
    Instagram = ""
    Wechat = "/images/wechat.jpeg"  # Wechat QRcode image
    #Facebook = "AKABinGo"
    Telegram = "BinGo_Huang"
    Dribbble = ""
    Medium = ""
